# Generated by Django 4.1.7 on 2023-06-24 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminid', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('nama_admin', models.CharField(max_length=200)),
                ('divisi', models.CharField(max_length=200)),
                ('kedinasan', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Fasilitas_perlengkapan',
            fields=[
                ('fasilitasid', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('nama_fasilitas', models.CharField(max_length=200)),
                ('kondisi', models.CharField(max_length=200)),
                ('volume', models.IntegerField()),
                ('gambar', models.ImageField(null=True, upload_to='fasilitas/')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('locationid', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Masyarakat',
            fields=[
                ('masyarakatid', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=200)),
                ('notelepon', models.IntegerField()),
                ('alamat', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pembangunan',
            fields=[
                ('pembangunanid', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('tanggal_bangun', models.DateField()),
                ('konstruksi_selesai', models.DateField()),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.location')),
            ],
        ),
        migrations.CreateModel(
            name='Perlengkapan_jalan',
            fields=[
                ('perlengkapanid', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('jenis_perlengkapan', models.CharField(max_length=200, unique=True)),
                ('deskrpsi', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('statusid', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('tipestatus', models.CharField(choices=[('DIAJUKAN', 'Masih Diajukan'), ('DIPROSES', 'Masih Diproses'), ('PERENCANAAN', 'Perencanaan'), ('PEMBANGUNAN', 'Pembangunan')], default='DIAJUKAN', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perencanaan',
            fields=[
                ('perencanaanid', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('nama_perencanaan', models.CharField(max_length=200)),
                ('fasilitasid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fasilitas_perlengkapan')),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.location')),
                ('pembangunanid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pembangunan')),
                ('status_pengajuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.status', to_field='tipestatus')),
            ],
        ),
        migrations.CreateModel(
            name='Penyeleksian',
            fields=[
                ('penyeleksianid', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('adminid', models.CharField(max_length=200)),
                ('pengajuanid', models.CharField(max_length=200)),
                ('perencanaanid', models.CharField(max_length=200)),
                ('tggl_terima', models.DateTimeField()),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.location')),
                ('pembangunanid', models.ManyToManyField(to='core.pembangunan')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.status', to_field='tipestatus')),
            ],
        ),
        migrations.CreateModel(
            name='Pengajuan',
            fields=[
                ('pengajuanid', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.location')),
                ('masyarakatid', models.ManyToManyField(to='core.masyarakat')),
                ('nama_fasilitas', models.ManyToManyField(to='core.fasilitas_perlengkapan')),
                ('perlengkapanid', models.ManyToManyField(to='core.perlengkapan_jalan')),
                ('statuspengajuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.status')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='status',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.status'),
        ),
        migrations.AddField(
            model_name='fasilitas_perlengkapan',
            name='jenis_perlengkapan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.perlengkapan_jalan', to_field='jenis_perlengkapan'),
        ),
        migrations.AddField(
            model_name='fasilitas_perlengkapan',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.status', to_field='tipestatus'),
        ),
        migrations.CreateModel(
            name='Beranda',
            fields=[
                ('folioid', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('jenis_perlengkapan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.perlengkapan_jalan', to_field='jenis_perlengkapan')),
                ('konstruksi_selesai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pembangunan')),
                ('nama_perencanaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.perencanaan')),
            ],
        ),
    ]
