# Generated by Django 4.1.7 on 2023-06-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fasilitas_perlengkapan',
            name='gambar',
            field=models.ImageField(null=True, upload_to='fasilitas/'),
        ),
    ]
