# Generated by Django 4.1.7 on 2023-06-24 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nama_admin',
            new_name='nama_user',
        ),
    ]
