# Generated by Django 4.1.7 on 2023-07-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_fasilitas_perlengkapan_tipekhusus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fasilitas_perlengkapan',
            name='gambar',
            field=models.ImageField(null=True, upload_to='fasilitas/%Y/%m/%d/'),
        ),
    ]
