# Generated by Django 4.1.7 on 2023-06-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_fasilitas_perlengkapan_gambar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='tipestatus',
            field=models.CharField(choices=[('DIAJUKAN', 'Masih Diajukan'), ('DIPROSES', 'Masih Diproses'), ('PERENCANAAN', 'Perencanaan'), ('PEMBANGUNAN', 'Pembangunan')], default='DIAJUKAN', max_length=50, unique=True),
        ),
    ]
