# Generated by Django 4.1.7 on 2023-06-12 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_status_tipestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='fasilitas_perlengkapan',
            name='status',
            field=models.ForeignKey(default='exit', on_delete=django.db.models.deletion.CASCADE, to='core.status', to_field='tipestatus'),
            preserve_default=False,
        ),
    ]
