# Generated by Django 4.1.7 on 2023-07-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_fasilitas_perlengkapan_gambar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fasilitas_perlengkapan',
            name='tipekhusus',
            field=models.CharField(max_length=200),
        ),
    ]
