# Generated by Django 4.1.7 on 2023-06-24 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_nama_admin_user_nama_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nama_user',
        ),
    ]
