# Generated by Django 4.1.7 on 2023-07-05 14:34

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_fasilitas_perlengkapan_gambar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fasilitas_perlengkapan',
            name='gambar',
            field=models.ImageField(blank=True, upload_to=core.models.upload_to),
        ),
    ]
