# Generated by Django 4.1.7 on 2023-07-07 08:10

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_fasilitas_perlengkapan_gambar'),
    ]

    operations = [
        migrations.AddField(
            model_name='pembangunan',
            name='gambar',
            field=models.ImageField(blank=True, upload_to=core.models.upload_to),
        ),
        migrations.AddField(
            model_name='pengajuan',
            name='gambar',
            field=models.ImageField(blank=True, upload_to=core.models.upload_to),
        ),
        migrations.AddField(
            model_name='perencanaan',
            name='gambar',
            field=models.ImageField(blank=True, upload_to=core.models.upload_to),
        ),
    ]
