# Generated by Django 4.1.7 on 2023-07-07 08:18

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_pembangunan_gambar_pengajuan_gambar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembangunan',
            name='gambar',
            field=models.ImageField(blank=True, upload_to=core.models.cringe),
        ),
        migrations.AlterField(
            model_name='pengajuan',
            name='gambar',
            field=models.ImageField(blank=True, upload_to=core.models.mirage),
        ),
        migrations.AlterField(
            model_name='perencanaan',
            name='gambar',
            field=models.ImageField(blank=True, upload_to=core.models.demonslayer),
        ),
    ]
