# Generated by Django 4.1.7 on 2023-07-07 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_pembangunan_status_pengajuan_fasilitas_khusus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pengajuan',
            name='perlengkapanid',
        ),
        migrations.AddField(
            model_name='pengajuan',
            name='jenis_perlengkapan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.perlengkapan_jalan', to_field='jenis_perlengkapan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fasilitas_perlengkapan',
            name='nama_fasilitas',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.RemoveField(
            model_name='pengajuan',
            name='nama_fasilitas',
        ),
        migrations.AddField(
            model_name='pengajuan',
            name='nama_fasilitas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.fasilitas_perlengkapan', to_field='nama_fasilitas'),
            preserve_default=False,
        ),
    ]
