# Generated by Django 4.1.7 on 2023-07-09 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_pengajuan_perlengkapanid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fasilitas_perlengkapan',
            name='kondisi',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='fasilitas_perlengkapan',
            name='volume',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='pengajuan',
            name='jenis_perlengkapan',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.perlengkapan_jalan', to_field='jenis_perlengkapan'),
        ),
        migrations.AlterField(
            model_name='pengajuan',
            name='nama_fasilitas',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.fasilitas_perlengkapan', to_field='nama_fasilitas'),
        ),
    ]
