# Generated by Django 4.1.7 on 2023-07-11 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_fasilitas_perlengkapan_kondisi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengajuan',
            name='statuspengajuan',
            field=models.OneToOneField(default='DIAJUKAN', on_delete=django.db.models.deletion.CASCADE, to='core.status'),
        ),
    ]
