# Generated by Django 4.1.7 on 2023-07-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_pengajuan_statuspengajuan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masyarakat',
            name='notelepon',
            field=models.CharField(max_length=30),
        ),
    ]
