# Generated by Django 4.1.7 on 2023-07-11 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_masyarakat_notelepon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pengajuan',
            name='masyarakatid',
        ),
        migrations.AddField(
            model_name='pengajuan',
            name='masyarakatid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.masyarakat'),
            preserve_default=False,
        ),
    ]
