# Generated by Django 4.1.7 on 2023-07-11 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_pengajuan_masyarakatid_pengajuan_masyarakatid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengajuan',
            name='statuspengajuan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.status'),
        ),
    ]
