# Generated by Django 4.1.7 on 2023-07-12 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_location_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='tipestatus',
            field=models.CharField(choices=[('DIAJUKAN', 'Masih Diajukan'), ('DIPROSES', 'Masih Diproses'), ('PERENCANAAN', 'Perencanaan'), ('PEMBANGUNAN', 'Pembangunan')], default='DIAJUKAN', max_length=50),
        ),
    ]
