# Generated by Django 4.1.7 on 2023-07-13 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_status_tipestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='pembangunan',
            name='jenis_perlengkapan',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='core.perlengkapan_jalan', to_field='jenis_perlengkapan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pembangunan',
            name='kondisi',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pembangunan',
            name='nama_fasilitas',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='core.fasilitas_perlengkapan', to_field='nama_fasilitas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pembangunan',
            name='volume',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
