# Generated by Django 4.1.7 on 2023-07-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_kerusakan_kondisi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembangunan',
            name='konstruksi_selesai',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pembangunan',
            name='tanggal_bangun',
            field=models.CharField(max_length=200),
        ),
    ]
