# Generated by Django 4.1.7 on 2023-07-14 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_pembangunan_konstruksi_selesai_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembangunan',
            name='kondisi',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.kondisi'),
        ),
        migrations.AlterField(
            model_name='pembangunan',
            name='konstruksi_selesai',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pembangunan',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.location'),
        ),
        migrations.AlterField(
            model_name='pembangunan',
            name='status',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.status'),
        ),
        migrations.AlterField(
            model_name='pembangunan',
            name='tanggal_bangun',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pembangunan',
            name='volume',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perencanaan',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.location'),
        ),
        migrations.AlterField(
            model_name='perencanaan',
            name='status_pengajuan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.status'),
        ),
    ]
