# Generated by Django 4.1.7 on 2023-07-14 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_pembangunan_kondisi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembangunan',
            name='kondisi',
            field=models.OneToOneField(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='core.kondisi'),
            preserve_default=False,
        ),
    ]
