# Generated by Django 4.1.7 on 2023-07-14 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_pembangunan_kondisi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembangunan',
            name='kondisi',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.kondisi'),
        ),
        migrations.AlterField(
            model_name='pembangunan',
            name='location',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.location'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pembangunan',
            name='status',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.status'),
            preserve_default=False,
        ),
    ]
