# Generated by Django 4.1.7 on 2023-07-14 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_pembangunan_kondisi_alter_pembangunan_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembangunan',
            name='kondisi',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.kondisi'),
        ),
        migrations.AlterField(
            model_name='pembangunan',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.location'),
        ),
        migrations.AlterField(
            model_name='pembangunan',
            name='status',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.status'),
        ),
    ]
