# Generated by Django 4.1.7 on 2023-07-15 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_pembangunan_kondisi_alter_pembangunan_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perencanaan',
            name='nama_perencanaan',
        ),
        migrations.RemoveField(
            model_name='perencanaan',
            name='status_pengajuan',
        ),
        migrations.AddField(
            model_name='perencanaan',
            name='deskripsi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perencanaan',
            name='kondisi',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='core.kondisi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perencanaan',
            name='konstruksi_selesai',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='perencanaan',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.status'),
        ),
        migrations.AddField(
            model_name='perencanaan',
            name='tanggal_bangun',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='perencanaan',
            name='volume',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
