# Generated by Django 4.1.7 on 2023-07-15 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_fasilitas_perlengkapan_tanggal_ditambahkan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fasilitas_perlengkapan',
            name='deskrpsi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
