# Generated by Django 4.1.7 on 2023-07-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_fasilitas_perlengkapan_deskrpsi'),
    ]

    operations = [
        migrations.AddField(
            model_name='fasilitas_perlengkapan',
            name='namakhusus',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
