# Generated by Django 4.1.7 on 2023-07-15 08:59

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_fasilitas_perlengkapan_namakhusus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fasilitas_perlengkapan',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.upload_to),
        ),
        migrations.AlterField(
            model_name='fasilitas_perlengkapan',
            name='nama_fasilitas',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
