# Generated by Django 4.1.7 on 2023-07-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_pembangunan_gambar_alter_pengajuan_gambar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='nama_admin',
            field=models.CharField(max_length=200),
        ),
    ]
