# Generated by Django 4.1.7 on 2023-07-16 13:24

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_admin_nama_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.common),
        ),
    ]
