# Generated by Django 4.1.7 on 2023-07-17 10:51

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_admin_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengajuan',
            name='gambar',
            field=models.ImageField(null=True, upload_to=core.models.mirage),
        ),
    ]
