# Generated by Django 4.1.7 on 2023-07-17 17:33

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_pengajuan_gambar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengajuan',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.mirage),
        ),
    ]
