# Generated by Django 4.1.7 on 2023-07-18 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_rusak_rename_deskrpsi_kerusakan_deskripsi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kerusakan',
            name='kondisi',
        ),
        migrations.RemoveField(
            model_name='kerusakan',
            name='konstruksi_selesai',
        ),
        migrations.RemoveField(
            model_name='kerusakan',
            name='status',
        ),
        migrations.RemoveField(
            model_name='kerusakan',
            name='tanggal_bangun',
        ),
        migrations.RemoveField(
            model_name='kerusakan',
            name='volume',
        ),
        migrations.AddField(
            model_name='kerusakan',
            name='rusak',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.rusak'),
        ),
        migrations.AlterField(
            model_name='kerusakan',
            name='jenis_perlengkapan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.perlengkapan_jalan', to_field='jenis_perlengkapan'),
        ),
        migrations.AlterField(
            model_name='kerusakan',
            name='nama_fasilitas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.fasilitas_perlengkapan', to_field='nama_fasilitas'),
        ),
        migrations.AlterField(
            model_name='penyeleksian',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.status'),
        ),
        migrations.AlterField(
            model_name='status',
            name='tipestatus',
            field=models.CharField(choices=[('DIAJUKAN', 'Masih Diajukan'), ('PERENCANAAN', 'Perencanaan'), ('PEMBANGUNAN', 'Pembangunan')], default='DIAJUKAN', max_length=50),
        ),
    ]
