# Generated by Django 4.1.7 on 2023-07-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_remove_kerusakan_kondisi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fasilitas_perlengkapan',
            name='color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='pembangunan',
            name='ruasjalan',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
