# Generated by Django 4.1.7 on 2023-07-23 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_fasilitas_perlengkapan_color_pembangunan_ruasjalan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kerusakan',
            old_name='perencanaanid',
            new_name='kerusakanid',
        ),
        migrations.AddField(
            model_name='kerusakan',
            name='masyarakatid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.masyarakat'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Penyeleksian',
        ),
    ]
