# Generated by Django 4.1.7 on 2023-08-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_rename_perencanaanid_kerusakan_kerusakanid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengajuan',
            name='tanggal_ajukan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pembangunan',
            name='konstruksi_selesai',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
