# Generated by Django 4.1.7 on 2023-08-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_pengajuan_tanggal_ajukan'),
    ]

    operations = [
        migrations.AddField(
            model_name='kerusakan',
            name='tanggal_laporkan',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
