# Generated by Django 4.1.7 on 2023-08-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_kerusakan_tanggal_laporkan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembangunan',
            name='tanggal_bangun',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
