# Generated by Django 4.1.7 on 2023-08-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_pembangunan_tanggal_bangun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fasilitas_perlengkapan',
            name='tanggal_ditambahkan',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
